version: '3.8'

services:
  nginx:
    container_name: static
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./results:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - server-network

  app:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/workspaces/app
    env_file:
      - .env
    networks:
      - server-network

networks:
  server-network: {}